### ISSUE TITLE
No parameter validation in any functions

### ISSUE THREAD

**Issue by IAXES** [zserge/jsmn#90]
If the client application doesn't properly initialize the context variable (ie: `jsmn_parser p`), the various API functions will potentially issue indirection operations on invalid/NULL pointers. I think this code would benefit from additional sanity checks at the beginning of each function, and changing the API a little bit (ie: no `void` functions, everything has a return code).

Do you have any concerns with this? If it sounds reasonable, I can put the changes in place easily enough, and have a pull request available fairly soon.

**Comment by pt300** [comment]
What I have to say about it:
1. I don't see the point in checking `jsmn_parser` for null since it's just 3 ints which is normally going to be allocated on stack.
2. Check if tokens == NULL is already in [code](https://github.com/zserge/jsmn/blob/master/jsmn.c#L166).
3. If `jsmn_parser` would be passed uninitialized nothing bad would happen anyway since `jsmn_parse()` would die in [beginning of `for` loop](https://github.com/zserge/jsmn/blob/master/jsmn.c#L158) if `pos > len` OR[ after calling](https://github.com/zserge/jsmn/blob/master/jsmn.c#L170) `jsmn_alloc_token()` if [toknext > num_tokens](https://github.com/zserge/jsmn/blob/master/jsmn.c#L9).
4. `jsmn_parse()` already has return codes and `jsmn_init()` has literally nothing to return. Rest are static functions.

**Comment by IAXES** [comment]
Sounds fair enough. Closing.
